document.writeln("    <div class=\'nav\'>");
document.writeln("        <img src=\'/picture/0/1706221004574115714.png\' alt=\'\'/>");
document.writeln("        <div class=\'main_nav\'>");
document.writeln("            <ul>");
document.writeln("                <li><a href=\'#\' class=\'active\'>首页</a></li>");
document.writeln("                <li><a href=\'#\'>通知公告</a></li>");
document.writeln("                <li><a href=\'#\'>政策法规</a></li>");
document.writeln("                <li><a href=\'#\'>办事指南</a></li>");
document.writeln("                <li><a href=\'#\'>综合查询</a></li>");
document.writeln("                <li><a href=\'#\'>互动交流</a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        <div class=\'top_nav_right\'>");
document.writeln("            <ul>");
document.writeln("                <li>");
document.writeln("                    <a id=\'btn_search\' style=\'cursor:pointer;\'>");
document.writeln("                        <img src=\'/picture/0/1706221005260092011.png\' alt=\'\'/>");
document.writeln("                    </a>");
document.writeln("                </li>");
document.writeln("                <li><a href=\'#\'>总局</a></li>");
document.writeln("                <li><a href=\'#\'>简</a></li>");
document.writeln("                <li><a href=\'#\'>繁</a></li>");
document.writeln("                <li><a href=\'#\'>EN</a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");